- name: Install kubeadm, kubelet, kubectl
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: true

- name: Join Kubernetes cluster
  shell: {{ hostvars['master-node']['join_command'] }}
  when: hostvars['master-node']['join_command'] is defined
