all:
  children:
    master:
      hosts:
        master-node:
          ansible_host: 192.168.1.10
    workers:
      hosts:
        worker-node1:
          ansible_host: 192.168.1.11
        worker-node2:
          ansible_host: 192.168.1.12